### PR TITLE
Support for Safari and iPhone Safari

### PR DESCRIPTION
**Pull request by ubahnverleih**
Added Support for Safari and mobile Safari.
* added `fetch` polyfill
* fixed viewport for mobile
* added overflow scroll for sidebar

### CODE REVIEW

**Comment by rashfael** [comment]
Thanks!
I don't have an iDevice, so I can't test it for Safari, working for mobile Chrome.

Does the scroll-overflow help anything on Safari, doesn't make that much sense for Chrome.
Sidebar should be responsive and dismissable anyway.

**Comment by ubahnverleih** [comment]
Overflow scroll also helps in Desktop browser, when showing more sensors in sidebar. (zoomed out)

**Comment by rashfael** [comment]
That would be `overflow-y`, not `overflow-x` though, if we wan't the vertical list to be scrollable.

**Comment by ubahnverleih** [comment]
ok, `overflow-y` would be the right one and i don't know why `overflow-x` has the same effect. And `auto` would be the better value

**Comment by ubahnverleih** [comment]
fixed in PR #12

**Comment by rashfael** [comment]
overflow is a bit quirky, certain combinations for x/y are not possible: http://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue/6433475#6433475

**Pull request merged**
