### PR TITLE
Updated Legend and Background Map

### PR DESCRIPTION
**Pull request by ubahnverleih**
* Updated Legend to show values from 0-500, but 0-100 takes 80% of the Space
* Some CSS Colorfilters for the OSM maptiles, inspired by https://michaelkreil.github.io/feinstaub-map/ by @michaelkreil

### CODE REVIEW

**Comment by BrunoKestemont** [comment]
The choice of background map.
Would it be possible to directly select OpenStreetMap (which is of a higher resolution)
https://www.openstreetmap.org
or any Google or other ones?
The current map is of too low resolution (streets are not big enough).

**Comment by ricki-z** [comment]
The actual map IS openstreetmap. We have only installed a proxy to limit the traffic on the openstreetmap servers.

**Comment by BrunoKestemont** [comment]
ok but is there any way to take a high resolution piece of OSM when further zooming? We need a resolution until the houses in a street because of likely different monitoring around schools for example.

**Comment by ricki-z** [comment]
You could download the source of this map and build your own version. You only need to change the max zoom level in the file map.vue. But the max. resolution of the station data won't be changed by this. We are rounding the location data to 1/500 degree. This is mentioned in our FAQ. To change this we would need to contact all exisiting sensor owners (more than 9000 at the moment) as we need to ask if a higher accuracy is okay.

**Pull request merged**
